{% set name = "dataframe_image" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d6739da53c66bd557f217237bab45943a452760b808bb7a3e635a939eed0bb5

build:
  number: 1
  noarch: python
  entry_points:
    - dataframe_image=dataframe_image._command_line:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - aiohttp
    - beautifulsoup4
    - matplotlib-base >=3.1
    - nbconvert >=5
    - pandas >=0.24
    - python >={{ python_min }}
    - requests

test:
  imports:
    - dataframe_image
    - tests
  commands:
    - pip check
    - dataframe_image --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dexplo/dataframe_image
  summary: Embed pandas DataFrames as images in pdf and markdown files when converting from Jupyter Notebooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdpetrou
